### ISSUE TITLE
Is the README.md wrong?

### ISSUE THREAD

**Issue by schinery** [arvidkahl/grunt-translate-sync#2]
Hi,

In the current README.md the examples says to do this:

```
translate_sync: {
  options: {
    keepKeyOrder: Boolean,
    indent: String or Number
  },
  source: String,
  targets: [String]
}
```

Which I did, but then I was getting a '>> Source option not found.' error.

After some digging around the file tasks/translate_sync.js I saw that it trying to get the source (and target files) from:

``` JavaScript
var sourceFile = this.data.source;
var targetFiles = this.data.targets;
```

So I changed my grunt file to:

```
translate_sync: {
  options: {
    keepKeyOrder: Boolean,
    indent: String or Number
  },
  data: {
    source: String,
    targets: [String]
  }
}
```

And now everything is working.

So are the README.md examples wrong?

**Comment by hvva** [comment]
Had the same problem. Specifying data: { } solved the issue.
